service: angular-ssr-serverless-testing
frameworkVersion: "3"
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 192
  timeout: 20
  stage: production
  deploymentBucket:
    name: shiv-source-serverless-deployment-bucket
  apiGateway:
    binaryMediaTypes:
      - "*/*"

package:
  patterns:
    - "!.git"
    - "!./**"
    - "node_modules/aws-serverless-express/**"
    - "node_modules/@vendia/serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "dist/**"
    - "lambda.js"

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
